kind = "web"
previewPath = "/"
title = "ICT Club of NJBS"
version = "1.0.0"
id = "artifacts/ict-club"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21038

[services.development]
run = "pnpm --filter @workspace/ict-club run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ict-club", "run", "build" ]
publicDir = "artifacts/ict-club/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21038"
BASE_PATH = "/"
